Repository GOORM-HIGH/tickle-frontend, pull requests merged in 2025-08, with the labels that each got.

#7 feat: 공통 header footer 생성
  src/components/layout/footer/Footer.tsx
  src/components/layout/header/Header.tsx
Labels: enhancement

#9 Feat/#1 chat frontend
  src/components/chat/ChatMessage.tsx
  src/components/chat/ChatRoom.tsx
  src/components/chat/EnhancedChatRoomList.tsx
  src/hooks/useChat.ts
  src/hooks/useReadStatus.ts
  src/pages/MainPage.tsx
  src/services/chatService.ts
  src/services/stompWebSocketService.ts
Labels: enhancement

#24 fix: 이벤트 페이지 에러 해결
  package-lock.json
  package.json
  src/feat-event/_components/coupon/CouponSection.tsx
  src/feat-event/pages/EventDetailPage.tsx
  src/feat-event/pages/EventPage.tsx
Labels: bug

#30 fix: event 에러 수정
  package.json
  src/components/chat/ChatInput.tsx
  src/components/common/Logo.tsx
  src/components/common/header/FeatureMenu.tsx
  src/feat-event/_components/common/index.ts
  src/feat-event/_components/ui/index.ts
  src/feat-event/api/eventApi.ts
  src/feat-event/components/common/index.ts
  src/feat-event/components/coupon/CouponCard.tsx
  src/feat-event/components/coupon/CouponSection.tsx
  src/feat-event/components/coupon/index.ts
  src/feat-event/components/event/CouponEventSection.tsx
  src/feat-event/components/event/EventDetails.tsx
  src/feat-event/components/event/EventHeader.tsx
  src/feat-event/components/event/EventPosterSection.tsx
  src/feat-event/components/event/EventSearchBar.tsx
  src/feat-event/components/event/HeroSection.tsx
  src/feat-event/components/event/PromotionalBanner.tsx
  src/feat-event/components/event/RecommendedEvents.tsx
  src/feat-event/components/event/ResultPopup.tsx
  src/feat-event/components/event/TabButtons.tsx
  src/feat-event/components/event/TicketEventSection.tsx
  src/feat-event/components/event/index.ts
  src/feat-event/components/index.ts
  src/feat-event/components/ticket/TicketEventCard.tsx
  src/feat-event/components/ticket/index.ts
  src/feat-event/components/ui/index.ts
  src/feat-event/pages/EventDetailPage.tsx
  src/feat-event/pages/EventPage.tsx
  src/feat-event/styles/event.module.css
  src/feat-point/components/Sidebar.tsx
  src/hooks/useAuth.ts
  src/hooks/useChat.ts
  src/hooks/useWebSocket.ts
  src/pages/MyPage.tsx
  src/utils/cookieUtils.ts
  src/utils/tokenUtils.ts
  tsconfig.app.json
  tsconfig.node.json
  vite.config.ts
Labels: bug, enhancement

#32 feat: 마이페이지 구현
  src/feat-mypage/components/ChargePopup.tsx
  src/feat-mypage/components/ReceiptPopup.tsx
  src/feat-mypage/components/Sidebar.tsx
  src/feat-mypage/components/TransactionTable.tsx
  src/feat-mypage/components/index.ts
  src/feat-mypage/index.ts
  src/feat-mypage/pages/MyPage.tsx
  src/feat-mypage/pages/PointChargePage.tsx
  src/feat-mypage/pages/PointHistoryPage.tsx
  src/feat-mypage/pages/ScrapPage.tsx
  src/feat-mypage/pages/index.ts
  src/feat-mypage/styles/MyPage.css
  src/feat-mypage/styles/carge.module.css
  src/feat-mypage/styles/history.css
  src/feat-mypage/styles/history.module.css
  src/feat-mypage/styles/index.ts
  src/feat-mypage/types/index.ts
  src/feat-point/components/CouponForm.tsx
  src/feat-point/components/EventForm.tsx
  src/feat-point/components/index.ts
  src/feat-point/pages/PointChargePage.tsx
  src/home/pages/MyPage.tsx
  src/home/styles/MyPage.css
  src/hooks/useChat.ts
  src/pages/MainPage.tsx
  src/pages/MyPage.css
  src/pages/MyPage.tsx
  src/pages/member/auth/SignInPage.tsx
  src/routes/mypageRouter.tsx
  src/routes/performanceRouter.tsx
  src/routes/totalRouter.tsx
  src/services/authService.ts
  src/services/pointService.ts
  src/utils/profanityFilter.ts
  src/utils/tokenUtils.ts
  src/vite-env.d.ts
Labels: enhancement

#43 bug: 회원정보가 표시되지 않는 오류 수정
  src/components/member/ProfileImageUploader.tsx
  src/feat-mypage/components/ProfileSection.tsx
  src/feat-mypage/components/tabs/InfoTab.tsx
  src/pages/member/auth/HostSignUpPage.tsx
  src/pages/member/auth/SignUpPage.tsx
Labels: bug

#52 fix: 라우팅 URL 수정
  src/pages/member/auth/SignInPage.tsx
  src/pages/member/auth/SignUpPage.tsx
Labels: bug

#54 fix: 라우팅 URL 수정
  src/pages/member/auth/SignInPage.tsx
Labels: bug
